#include "mapData.h"
#include "utility.h"

/***MAP DATA***/
const unsigned int mapDimX = MAPDIMX; //tails
const unsigned int mapDimY = MAPDIMY; //tails

//const unsigned int tailSize = 8; //px 8*8
const unsigned int pillSize = 2; //px 2*2
unsigned int offset; //pill offset

const unsigned int startXmap = 8; //px
const unsigned int startYmap = 55;

//Maze from level one of pacman, extrapoint 2: modified the spawn area to accomodate blinky
enum PacTails level0[] ={
	WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, 
	WALL, PILL, PILL, PILL, PILL, PILL, PILL, PILL, PILL, PILL, PILL, PILL, PILL, WALL, WALL, PILL, PILL, PILL, PILL, PILL, PILL, PILL, PILL, PILL, PILL, PILL, PILL, WALL,
	WALL, PILL, WALL, WALL, WALL, WALL, PILL, WALL, WALL, WALL, WALL, WALL, PILL, WALL, WALL, PILL, WALL, WALL, WALL, WALL, WALL, PILL, WALL, WALL, WALL, WALL, PILL, WALL,
	WALL, PILL, WALL, WALL, WALL, WALL, PILL, WALL, WALL, WALL, WALL, WALL, PILL, WALL, WALL, PILL, WALL, WALL, WALL, WALL, WALL, PILL, WALL, WALL, WALL, WALL, PILL, WALL,
	WALL, PILL, WALL, WALL, WALL, WALL, PILL, WALL, WALL, WALL, WALL, WALL, PILL, WALL, WALL, PILL, WALL, WALL, WALL, WALL, WALL, PILL, WALL, WALL, WALL, WALL, PILL, WALL,
	WALL, PILL, PILL, PILL, PILL, PILL, PILL, PILL, PILL, PILL, PILL, PILL, PILL, PILL, PILL, PILL, PILL, PILL, PILL, PILL, PILL, PILL, PILL, PILL, PILL, PILL, PILL, WALL,
	WALL, PILL, WALL, WALL, WALL, WALL, PILL, WALL, WALL, PILL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, PILL, WALL, WALL, PILL, WALL, WALL, WALL, WALL, PILL, WALL,
  WALL, PILL, WALL, WALL, WALL, WALL, PILL, WALL, WALL, PILL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, PILL, WALL, WALL, PILL, WALL, WALL, WALL, WALL, PILL, WALL,
	WALL, PILL, PILL, PILL, PILL, PILL, PILL, WALL, WALL, PILL, PILL, EMPT, EMPT, WALL, WALL, EMPT, EMPT, PILL, PILL, WALL, WALL, PILL, PILL, PILL, PILL, PILL, PILL, WALL,
	WALL, WALL, WALL, WALL, WALL, WALL, PILL, WALL, WALL, WALL, WALL, WALL, EMPT, WALL, WALL, EMPT, WALL, WALL, WALL, WALL, WALL, PILL, WALL, WALL, WALL, WALL, WALL, WALL, 
	EMPT, EMPT, EMPT, EMPT, EMPT, WALL, PILL, WALL, WALL, WALL, WALL, WALL, EMPT, WALL, WALL, EMPT, WALL, WALL, WALL, WALL, WALL, PILL, WALL, EMPT, EMPT, EMPT, EMPT, EMPT, 
	EMPT, EMPT, EMPT, EMPT, EMPT, WALL, PILL, WALL, WALL, EMPT, EMPT, EMPT, EMPT, EMPT, EMPT, EMPT, EMPT, EMPT, EMPT, WALL, WALL, PILL, WALL, EMPT, EMPT, EMPT, EMPT, EMPT, 
	EMPT, EMPT, EMPT, EMPT, EMPT, WALL, PILL, WALL, WALL, EMPT, SPAW, SPAW, SPAW, SPAW, SPAW, SPAW, SPAW, SPAW, EMPT, WALL, WALL, PILL, WALL, EMPT, EMPT, EMPT, EMPT, EMPT,
	WALL, WALL, WALL, WALL, WALL, WALL, PILL, WALL, WALL, EMPT, SPAW, EMPT, EMPT, EMPT, EMPT, EMPT, EMPT, SPAW, EMPT, WALL, WALL, PILL, WALL, WALL, WALL, WALL, WALL, WALL, 
	EMPT, EMPT, EMPT, EMPT, EMPT, EMPT, PILL, EMPT, EMPT, EMPT, SPAW, EMPT, EMPT, BLIN, EMPT, EMPT, EMPT, SPAW, EMPT, EMPT, EMPT, PILL, EMPT, EMPT, EMPT, EMPT, EMPT, EMPT,
	WALL, WALL, WALL, WALL, WALL, WALL, PILL, WALL, WALL, EMPT, SPAW, EMPT, EMPT, EMPT, EMPT, EMPT, EMPT, SPAW, EMPT, WALL, WALL, PILL, WALL, WALL, WALL, WALL, WALL, WALL, 
	EMPT, EMPT, EMPT, EMPT, EMPT, WALL, PILL, WALL, WALL, EMPT, SPAW, SPAW, SPAW, SPAW, SPAW, SPAW, SPAW, SPAW, EMPT, WALL, WALL, PILL, WALL, EMPT, EMPT, EMPT, EMPT, EMPT, 
	EMPT, EMPT, EMPT, EMPT, EMPT, WALL, PILL, WALL, WALL, EMPT, EMPT, EMPT, EMPT, EMPT, EMPT, EMPT, EMPT, EMPT, EMPT, WALL, WALL, PILL, WALL, EMPT, EMPT, EMPT, EMPT, EMPT, 
	EMPT, EMPT, EMPT, EMPT, EMPT, WALL, PILL, WALL, WALL, EMPT, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, EMPT, WALL, WALL, PILL, WALL, EMPT, EMPT, EMPT, EMPT, EMPT,
	WALL, WALL, WALL, WALL, WALL, WALL, PILL, WALL, WALL, EMPT, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, EMPT, WALL, WALL, PILL, WALL, WALL, WALL, WALL, WALL, WALL,
	WALL, PILL, PILL, PILL, PILL, PILL, PILL, PILL, PILL, PILL, PILL, PILL, PILL, WALL, WALL, PILL, PILL, PILL, PILL, PILL, PILL, PILL, PILL, PILL, PILL, PILL, PILL, WALL,
	WALL, PILL, WALL, WALL, WALL, WALL, PILL, WALL, WALL, WALL, WALL, WALL, PILL, WALL, WALL, PILL, WALL, WALL, WALL, WALL, WALL, PILL, WALL, WALL, WALL, WALL, PILL, WALL,
	WALL, PILL, WALL, WALL, WALL, WALL, PILL, WALL, WALL, WALL, WALL, WALL, PILL, WALL, WALL, PILL, WALL, WALL, WALL, WALL, WALL, PILL, WALL, WALL, WALL, WALL, PILL, WALL,
	WALL, PILL, PILL, PILL, WALL, WALL, PILL, PILL, PILL, PILL, PILL, PILL, PILL, PACM, EMPT, PILL, PILL, PILL, PILL, PILL, PILL, PILL, WALL, WALL, PILL, PILL, PILL, WALL,
	WALL, WALL, WALL, PILL, WALL, WALL, PILL, WALL, WALL, PILL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, PILL, WALL, WALL, PILL, WALL, WALL, PILL, WALL, WALL, WALL, 
	WALL, WALL, WALL, PILL, WALL, WALL, PILL, WALL, WALL, PILL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, PILL, WALL, WALL, PILL, WALL, WALL, PILL, WALL, WALL, WALL, 
	WALL, PILL, PILL, PILL, PILL, PILL, PILL, WALL, WALL, PILL, PILL, PILL, PILL, WALL, WALL, PILL, PILL, PILL, PILL, WALL, WALL, PILL, PILL, PILL, PILL, PILL, PILL, WALL,
	WALL, PILL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, PILL, WALL, WALL, PILL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, PILL, WALL,
	WALL, PILL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, PILL, WALL, WALL, PILL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, PILL, WALL,
	WALL, PILL, PILL, PILL, PILL, PILL, PILL, PILL, PILL, PILL, PILL, PILL, PILL, PILL, PILL, PILL, PILL, PILL, PILL, PILL, PILL, PILL, PILL, PILL, PILL, PILL, PILL, WALL,
	WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL
};

